import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button } from 'react-bootstrap'
import LoginButton from '../components/login-btn2'
import { SessionProvider } from 'next-auth/react'








export default function Home() {

  return (
    
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Ject.io</a>
        </h1>
        <p className={styles.description}>{"A Task tracking app built with NextJS and Xata.io"}</p>
        {/* <a href='/Dashboard'> */}
        <div className={styles.LoginButton}>
          <LoginButton />
        

        </div>
        {/* </a> */}

        </main>

      </div>
  )
}
